# Generated by Django 5.2.7 on 2026-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="about"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="facebook",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_host",
            field=models.BooleanField(default=False, verbose_name="is host account"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
