# Generated by Django 5.2.7 on 2026-01-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="telegram",
        ),
        migrations.AddField(
            model_name="customuser",
            name="contacts",
            field=models.TextField(blank=True, null=True, verbose_name="contacts"),
        ),
    ]
