# Generated by Django 5.2.7 on 2026-01-30 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_telegram_customuser_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Назва")),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("activity", "Активні вихідні"),
                            ("handmade", "Своїми руками"),
                            ("culture", "Екскурсії та відпочинок"),
                            ("food", "Їжа та дегустації"),
                            ("other", "Різне"),
                        ],
                        max_length=50,
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Наприклад: м. Київ, вул. Хрещатик, 1",
                        max_length=255,
                        verbose_name="Адреса",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        verbose_name="Максимальна кількість гостей"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="event_photos/", verbose_name="Фото"),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ціна за особу",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Приблизна тривалість",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата"),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Соціальні мережі"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attended_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Гості",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Враження",
                "verbose_name_plural": "Враження",
                "indexes": [
                    models.Index(
                        fields=["category"], name="users_event_categor_e81099_idx"
                    )
                ],
            },
        ),
    ]
