# Generated by Django 5.2.7 on 2026-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="social_links",
        ),
        migrations.AddField(
            model_name="event",
            name="social1",
            field=models.URLField(
                blank=True, null=True, verbose_name="Посилання на ваші соціальні мережі"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="social2",
            field=models.URLField(
                blank=True, null=True, verbose_name="Додаткові посилання"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(
                help_text="Наприклад: м. Київ, вул. Хрещатик, 1",
                max_length=255,
                verbose_name="Адреса *",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("activity", "Активні вихідні"),
                    ("handmade", "Своїми руками"),
                    ("culture", "Екскурсії та відпочинок"),
                    ("food", "Їжа та дегустації"),
                    ("other", "Різне"),
                ],
                max_length=50,
                verbose_name="Категорія *",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="Опис *"),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_guests",
            field=models.PositiveIntegerField(
                verbose_name="Максимальна кількість гостей *"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(upload_to="event_photos/", verbose_name="Фото *"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Назва *"),
        ),
    ]
