# Generated by Django 5.2.7 on 2026-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_event_social_links_event_social1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="event_photos/",
                verbose_name="Фото 2 (за бажанням)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="event_photos/",
                verbose_name="Фото 3 (за бажанням)",
            ),
        ),
    ]
