# Generated by Django 6.0 on 2026-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_event_social_links_event_social1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name="Ім'я автора")),
                ('location', models.CharField(blank=True, max_length=120, null=True, verbose_name='Локація')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Оцінка')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='review_avatars/', verbose_name='Аватар')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показувати у верхньому блоці')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
