# Generated by Django 6.0 on 2026-02-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_event_photo_2_event_photo_3'),
        ('users', '0008_review'),
    ]

    operations = [
    ]
